# -*- coding: utf-8 -*-
"""RTA .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18OkbKXOHnzB6DpdEyeBmJS8tRYnGgap9

**ReadMe:**

1. Fitstly, you should get your personal API though Alpha_Vantage https://www.alphavantage.co/support/#api-key
2. Intall the library alpha_vantage
3. Connected to 'APPLE Company'
"""

!pip install alpha_vantage

from alpha_vantage.timeseries import TimeSeries

API_key = 'CP79H1GMVOB7F5NW' # your personal API key 

ts = TimeSeries(key = API_key, output_format = 'pandas')

data = ts.get_intraday('AAPL',interval = '15min') # Apple company

data

# for fundamentaldata

from alpha_vantage.fundamentaldata import FundamentalData

key = 'CP79H1GMVOB7F5NW'

fd = FundamentalData(key,output_format='pandas')

data = fd.get_balance_sheet_annual('MSFT')

data[0].T

from alpha_vantage.timeseries import TimeSeries

key = 'CP79H1GMVOB7F5NW'
outputsize = 'compact'
symbol = input('Ticker : ')
typ= input('Data Type- "daily", "weekly","monthly","interval": ')

ts = TimeSeries(key,output_format='pandas')

if typ == 'daily':
  state = ts.get_daily_adjusted(symbol,outputsize=outputsize)[0]
elif typ == 'weekly':
  state = ts.get_weekly_adjusted(symbol)[0]
elif typ == 'monthly':
  state = ts.get_monthly_adjusted(symbol)[0]
elif typ == 'interval':
  interval = input("interval-1min,5min,15min,30min,60min: ")
  state = ts.get_intraday(symbol, interval = interval, outputsize=outputsize)[0]
else:
  print('wrong entry')
  state

