version: '3.4'

services:
  projectrta:
    image: projectrta
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn projectrta.app:app --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
